/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdminStats {
  'totalOrders' : bigint,
  'pendingWithdrawals' : bigint,
  'pendingOrders' : bigint,
  'totalCommissionsPaid' : bigint,
  'totalUsers' : bigint,
  'totalRevenue' : bigint,
  'netProfit' : bigint,
}
export interface AuditLog {
  'id' : bigint,
  'action' : string,
  'timestamp' : Timestamp,
  'details' : string,
  'targetUserId' : [] | [UserId],
}
export interface BankDetails {
  'ifsc' : string,
  'accountHolderName' : string,
  'accountNumber' : string,
}
export interface NotificationPublic {
  'id' : bigint,
  'isRead' : boolean,
  'message' : string,
  'timestamp' : Timestamp,
  'recipientId' : [] | [UserId],
}
export interface OrderPublic {
  'id' : bigint,
  'status' : OrderStatus,
  'deliveryAddress' : string,
  'planId' : bigint,
  'rejectionReason' : [] | [string],
  'planPrice' : bigint,
  'timestamp' : Timestamp,
  'buyer' : UserId,
  'utrScreenshotUrl' : [] | [string],
}
export type OrderStatus = { 'pendingApproval' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface PaymentDetails {
  'bankDetails' : [] | [BankDetails],
  'upiId' : [] | [string],
}
export interface Plan { 'id' : bigint, 'name' : string, 'price' : bigint }
export interface ProductPublic {
  'id' : bigint,
  'name' : string,
  'isActive' : boolean,
  'imageUrl' : [] | [string],
  'price' : bigint,
}
export type Timestamp = bigint;
export interface TreeNode {
  'name' : string,
  'user' : UserId,
  'children' : Array<TreeNode>,
}
export type UserId = string;
export interface UserPublic {
  'id' : UserId,
  'status' : UserStatus,
  'referralCode' : string,
  'directIncome' : bigint,
  'hasBankDetails' : boolean,
  'hasUpiId' : boolean,
  'rightChild' : [] | [UserId],
  'name' : string,
  'createdAt' : Timestamp,
  'sponsorId' : [] | [UserId],
  'totalIncome' : bigint,
  'levelIncome' : bigint,
  'leftChild' : [] | [UserId],
  'mobileNumber' : string,
  'isAdmin' : boolean,
  'position' : string,
  'pairIncome' : bigint,
  'walletBalance' : bigint,
}
export type UserStatus = { 'active' : null } |
  { 'hold' : null } |
  { 'inactive' : null };
export interface WalletInfo {
  'directIncome' : bigint,
  'balance' : bigint,
  'totalIncome' : bigint,
  'levelIncome' : bigint,
  'pairIncome' : bigint,
}
export interface WithdrawRequestPublic {
  'id' : bigint,
  'status' : WithdrawStatus,
  'user' : UserId,
  'processedAt' : [] | [Timestamp],
  'amount' : bigint,
  'requestedAt' : Timestamp,
}
export type WithdrawStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface _SERVICE {
  'adminAddProduct' : ActorMethod<
    [string, string, string, bigint, [] | [string]],
    { 'ok' : ProductPublic } |
      { 'err' : string }
  >,
  'adminApproveOrder' : ActorMethod<
    [string, string, bigint],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'adminApproveWithdrawal' : ActorMethod<
    [string, string, bigint],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'adminDeleteProduct' : ActorMethod<
    [string, string, bigint],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'adminGetAllOrders' : ActorMethod<
    [string, string],
    { 'ok' : Array<OrderPublic> } |
      { 'err' : string }
  >,
  'adminGetAllUsers' : ActorMethod<
    [string, string],
    { 'ok' : Array<UserPublic> } |
      { 'err' : string }
  >,
  'adminGetAllWithdrawals' : ActorMethod<
    [string, string],
    { 'ok' : Array<WithdrawRequestPublic> } |
      { 'err' : string }
  >,
  'adminGetAuditLog' : ActorMethod<
    [string, string],
    { 'ok' : Array<AuditLog> } |
      { 'err' : string }
  >,
  'adminGetNotificationHistory' : ActorMethod<
    [string, string],
    { 'ok' : Array<NotificationPublic> } |
      { 'err' : string }
  >,
  'adminGetPendingOrders' : ActorMethod<
    [string, string],
    { 'ok' : Array<OrderPublic> } |
      { 'err' : string }
  >,
  'adminGetProducts' : ActorMethod<
    [string, string],
    { 'ok' : Array<ProductPublic> } |
      { 'err' : string }
  >,
  'adminGetStats' : ActorMethod<
    [string, string],
    { 'ok' : AdminStats } |
      { 'err' : string }
  >,
  'adminLogin' : ActorMethod<
    [string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'adminRejectOrder' : ActorMethod<
    [string, string, bigint, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'adminRejectWithdrawal' : ActorMethod<
    [string, string, bigint],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'adminSendNotification' : ActorMethod<
    [string, string, [] | [UserId], string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'adminUpdateProduct' : ActorMethod<
    [string, string, bigint, string, bigint, [] | [string]],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'getDirectDownline' : ActorMethod<[UserId], Array<UserPublic>>,
  'getDownlineTree' : ActorMethod<
    [UserId],
    { 'ok' : TreeNode } |
      { 'err' : string }
  >,
  'getMyNotifications' : ActorMethod<[UserId], Array<NotificationPublic>>,
  'getMyOrders' : ActorMethod<[UserId], Array<OrderPublic>>,
  'getMyPaymentDetails' : ActorMethod<
    [UserId],
    { 'ok' : PaymentDetails } |
      { 'err' : string }
  >,
  'getMyProfile' : ActorMethod<
    [UserId],
    { 'ok' : UserPublic } |
      { 'err' : string }
  >,
  'getMyReferralCode' : ActorMethod<[UserId], string>,
  'getMyWallet' : ActorMethod<
    [UserId],
    { 'ok' : WalletInfo } |
      { 'err' : string }
  >,
  'getMyWithdrawals' : ActorMethod<[UserId], Array<WithdrawRequestPublic>>,
  'getPlans' : ActorMethod<[], Array<Plan>>,
  'getProducts' : ActorMethod<[], Array<ProductPublic>>,
  'getUserByMobile' : ActorMethod<[string], [] | [UserPublic]>,
  'loginUser' : ActorMethod<
    [string, string],
    { 'ok' : { 'userId' : UserId, 'profile' : UserPublic } } |
      { 'err' : string }
  >,
  'markNotificationRead' : ActorMethod<
    [UserId, bigint],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'purchasePlan' : ActorMethod<
    [UserId, bigint, string, [] | [string]],
    { 'ok' : OrderPublic } |
      { 'err' : string }
  >,
  'registerUser' : ActorMethod<
    [string, string, string, [] | [string], [] | [string]],
    { 'ok' : UserPublic } |
      { 'err' : string }
  >,
  'requestWithdrawal' : ActorMethod<
    [UserId, bigint],
    { 'ok' : WithdrawRequestPublic } |
      { 'err' : string }
  >,
  'resetUserPassword' : ActorMethod<
    [string, string, UserId, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'savePaymentDetails' : ActorMethod<
    [UserId, [] | [BankDetails], [] | [string]],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'setUserStatus' : ActorMethod<
    [string, string, UserId, UserStatus],
    { 'ok' : null } |
      { 'err' : string }
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];