/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const TreeNode = IDL.Rec();
export const ProductPublic = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'isActive' : IDL.Bool,
  'imageUrl' : IDL.Opt(IDL.Text),
  'price' : IDL.Nat,
});
export const OrderStatus = IDL.Variant({
  'pendingApproval' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const UserId = IDL.Text;
export const OrderPublic = IDL.Record({
  'id' : IDL.Nat,
  'status' : OrderStatus,
  'deliveryAddress' : IDL.Text,
  'planId' : IDL.Nat,
  'rejectionReason' : IDL.Opt(IDL.Text),
  'planPrice' : IDL.Nat,
  'timestamp' : Timestamp,
  'buyer' : UserId,
  'utrScreenshotUrl' : IDL.Opt(IDL.Text),
});
export const UserStatus = IDL.Variant({
  'active' : IDL.Null,
  'hold' : IDL.Null,
  'inactive' : IDL.Null,
});
export const UserPublic = IDL.Record({
  'id' : UserId,
  'status' : UserStatus,
  'referralCode' : IDL.Text,
  'directIncome' : IDL.Nat,
  'hasBankDetails' : IDL.Bool,
  'hasUpiId' : IDL.Bool,
  'rightChild' : IDL.Opt(UserId),
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'sponsorId' : IDL.Opt(UserId),
  'totalIncome' : IDL.Nat,
  'levelIncome' : IDL.Nat,
  'leftChild' : IDL.Opt(UserId),
  'mobileNumber' : IDL.Text,
  'isAdmin' : IDL.Bool,
  'position' : IDL.Text,
  'pairIncome' : IDL.Nat,
  'walletBalance' : IDL.Nat,
});
export const WithdrawStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const WithdrawRequestPublic = IDL.Record({
  'id' : IDL.Nat,
  'status' : WithdrawStatus,
  'user' : UserId,
  'processedAt' : IDL.Opt(Timestamp),
  'amount' : IDL.Nat,
  'requestedAt' : Timestamp,
});
export const AuditLog = IDL.Record({
  'id' : IDL.Nat,
  'action' : IDL.Text,
  'timestamp' : Timestamp,
  'details' : IDL.Text,
  'targetUserId' : IDL.Opt(UserId),
});
export const NotificationPublic = IDL.Record({
  'id' : IDL.Nat,
  'isRead' : IDL.Bool,
  'message' : IDL.Text,
  'timestamp' : Timestamp,
  'recipientId' : IDL.Opt(UserId),
});
export const AdminStats = IDL.Record({
  'totalOrders' : IDL.Nat,
  'pendingWithdrawals' : IDL.Nat,
  'pendingOrders' : IDL.Nat,
  'totalCommissionsPaid' : IDL.Nat,
  'totalUsers' : IDL.Nat,
  'totalRevenue' : IDL.Nat,
  'netProfit' : IDL.Nat,
});
TreeNode.fill(
  IDL.Record({
    'name' : IDL.Text,
    'user' : UserId,
    'children' : IDL.Vec(TreeNode),
  })
);
export const BankDetails = IDL.Record({
  'ifsc' : IDL.Text,
  'accountHolderName' : IDL.Text,
  'accountNumber' : IDL.Text,
});
export const PaymentDetails = IDL.Record({
  'bankDetails' : IDL.Opt(BankDetails),
  'upiId' : IDL.Opt(IDL.Text),
});
export const WalletInfo = IDL.Record({
  'directIncome' : IDL.Nat,
  'balance' : IDL.Nat,
  'totalIncome' : IDL.Nat,
  'levelIncome' : IDL.Nat,
  'pairIncome' : IDL.Nat,
});
export const Plan = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'price' : IDL.Nat,
});

export const idlService = IDL.Service({
  'adminAddProduct' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Opt(IDL.Text)],
      [IDL.Variant({ 'ok' : ProductPublic, 'err' : IDL.Text })],
      [],
    ),
  'adminApproveOrder' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'adminApproveWithdrawal' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'adminDeleteProduct' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'adminGetAllOrders' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Vec(OrderPublic), 'err' : IDL.Text })],
      [],
    ),
  'adminGetAllUsers' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Vec(UserPublic), 'err' : IDL.Text })],
      [],
    ),
  'adminGetAllWithdrawals' : IDL.Func(
      [IDL.Text, IDL.Text],
      [
        IDL.Variant({
          'ok' : IDL.Vec(WithdrawRequestPublic),
          'err' : IDL.Text,
        }),
      ],
      [],
    ),
  'adminGetAuditLog' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Vec(AuditLog), 'err' : IDL.Text })],
      [],
    ),
  'adminGetNotificationHistory' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Vec(NotificationPublic), 'err' : IDL.Text })],
      [],
    ),
  'adminGetPendingOrders' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Vec(OrderPublic), 'err' : IDL.Text })],
      [],
    ),
  'adminGetProducts' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Vec(ProductPublic), 'err' : IDL.Text })],
      [],
    ),
  'adminGetStats' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : AdminStats, 'err' : IDL.Text })],
      [],
    ),
  'adminLogin' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'adminRejectOrder' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'adminRejectWithdrawal' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'adminSendNotification' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(UserId), IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'adminUpdateProduct' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Nat, IDL.Opt(IDL.Text)],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'getDirectDownline' : IDL.Func([UserId], [IDL.Vec(UserPublic)], ['query']),
  'getDownlineTree' : IDL.Func(
      [UserId],
      [IDL.Variant({ 'ok' : TreeNode, 'err' : IDL.Text })],
      ['query'],
    ),
  'getMyNotifications' : IDL.Func(
      [UserId],
      [IDL.Vec(NotificationPublic)],
      ['query'],
    ),
  'getMyOrders' : IDL.Func([UserId], [IDL.Vec(OrderPublic)], ['query']),
  'getMyPaymentDetails' : IDL.Func(
      [UserId],
      [IDL.Variant({ 'ok' : PaymentDetails, 'err' : IDL.Text })],
      ['query'],
    ),
  'getMyProfile' : IDL.Func(
      [UserId],
      [IDL.Variant({ 'ok' : UserPublic, 'err' : IDL.Text })],
      ['query'],
    ),
  'getMyReferralCode' : IDL.Func([UserId], [IDL.Text], ['query']),
  'getMyWallet' : IDL.Func(
      [UserId],
      [IDL.Variant({ 'ok' : WalletInfo, 'err' : IDL.Text })],
      ['query'],
    ),
  'getMyWithdrawals' : IDL.Func(
      [UserId],
      [IDL.Vec(WithdrawRequestPublic)],
      ['query'],
    ),
  'getPlans' : IDL.Func([], [IDL.Vec(Plan)], ['query']),
  'getProducts' : IDL.Func([], [IDL.Vec(ProductPublic)], ['query']),
  'getUserByMobile' : IDL.Func([IDL.Text], [IDL.Opt(UserPublic)], ['query']),
  'loginUser' : IDL.Func(
      [IDL.Text, IDL.Text],
      [
        IDL.Variant({
          'ok' : IDL.Record({ 'userId' : UserId, 'profile' : UserPublic }),
          'err' : IDL.Text,
        }),
      ],
      [],
    ),
  'markNotificationRead' : IDL.Func(
      [UserId, IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'purchasePlan' : IDL.Func(
      [UserId, IDL.Nat, IDL.Text, IDL.Opt(IDL.Text)],
      [IDL.Variant({ 'ok' : OrderPublic, 'err' : IDL.Text })],
      [],
    ),
  'registerUser' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
      [IDL.Variant({ 'ok' : UserPublic, 'err' : IDL.Text })],
      [],
    ),
  'requestWithdrawal' : IDL.Func(
      [UserId, IDL.Nat],
      [IDL.Variant({ 'ok' : WithdrawRequestPublic, 'err' : IDL.Text })],
      [],
    ),
  'resetUserPassword' : IDL.Func(
      [IDL.Text, IDL.Text, UserId, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'savePaymentDetails' : IDL.Func(
      [UserId, IDL.Opt(BankDetails), IDL.Opt(IDL.Text)],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'setUserStatus' : IDL.Func(
      [IDL.Text, IDL.Text, UserId, UserStatus],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const TreeNode = IDL.Rec();
  const ProductPublic = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'isActive' : IDL.Bool,
    'imageUrl' : IDL.Opt(IDL.Text),
    'price' : IDL.Nat,
  });
  const OrderStatus = IDL.Variant({
    'pendingApproval' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const UserId = IDL.Text;
  const OrderPublic = IDL.Record({
    'id' : IDL.Nat,
    'status' : OrderStatus,
    'deliveryAddress' : IDL.Text,
    'planId' : IDL.Nat,
    'rejectionReason' : IDL.Opt(IDL.Text),
    'planPrice' : IDL.Nat,
    'timestamp' : Timestamp,
    'buyer' : UserId,
    'utrScreenshotUrl' : IDL.Opt(IDL.Text),
  });
  const UserStatus = IDL.Variant({
    'active' : IDL.Null,
    'hold' : IDL.Null,
    'inactive' : IDL.Null,
  });
  const UserPublic = IDL.Record({
    'id' : UserId,
    'status' : UserStatus,
    'referralCode' : IDL.Text,
    'directIncome' : IDL.Nat,
    'hasBankDetails' : IDL.Bool,
    'hasUpiId' : IDL.Bool,
    'rightChild' : IDL.Opt(UserId),
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'sponsorId' : IDL.Opt(UserId),
    'totalIncome' : IDL.Nat,
    'levelIncome' : IDL.Nat,
    'leftChild' : IDL.Opt(UserId),
    'mobileNumber' : IDL.Text,
    'isAdmin' : IDL.Bool,
    'position' : IDL.Text,
    'pairIncome' : IDL.Nat,
    'walletBalance' : IDL.Nat,
  });
  const WithdrawStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const WithdrawRequestPublic = IDL.Record({
    'id' : IDL.Nat,
    'status' : WithdrawStatus,
    'user' : UserId,
    'processedAt' : IDL.Opt(Timestamp),
    'amount' : IDL.Nat,
    'requestedAt' : Timestamp,
  });
  const AuditLog = IDL.Record({
    'id' : IDL.Nat,
    'action' : IDL.Text,
    'timestamp' : Timestamp,
    'details' : IDL.Text,
    'targetUserId' : IDL.Opt(UserId),
  });
  const NotificationPublic = IDL.Record({
    'id' : IDL.Nat,
    'isRead' : IDL.Bool,
    'message' : IDL.Text,
    'timestamp' : Timestamp,
    'recipientId' : IDL.Opt(UserId),
  });
  const AdminStats = IDL.Record({
    'totalOrders' : IDL.Nat,
    'pendingWithdrawals' : IDL.Nat,
    'pendingOrders' : IDL.Nat,
    'totalCommissionsPaid' : IDL.Nat,
    'totalUsers' : IDL.Nat,
    'totalRevenue' : IDL.Nat,
    'netProfit' : IDL.Nat,
  });
  TreeNode.fill(
    IDL.Record({
      'name' : IDL.Text,
      'user' : UserId,
      'children' : IDL.Vec(TreeNode),
    })
  );
  const BankDetails = IDL.Record({
    'ifsc' : IDL.Text,
    'accountHolderName' : IDL.Text,
    'accountNumber' : IDL.Text,
  });
  const PaymentDetails = IDL.Record({
    'bankDetails' : IDL.Opt(BankDetails),
    'upiId' : IDL.Opt(IDL.Text),
  });
  const WalletInfo = IDL.Record({
    'directIncome' : IDL.Nat,
    'balance' : IDL.Nat,
    'totalIncome' : IDL.Nat,
    'levelIncome' : IDL.Nat,
    'pairIncome' : IDL.Nat,
  });
  const Plan = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'price' : IDL.Nat,
  });
  
  return IDL.Service({
    'adminAddProduct' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Opt(IDL.Text)],
        [IDL.Variant({ 'ok' : ProductPublic, 'err' : IDL.Text })],
        [],
      ),
    'adminApproveOrder' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'adminApproveWithdrawal' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'adminDeleteProduct' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'adminGetAllOrders' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Vec(OrderPublic), 'err' : IDL.Text })],
        [],
      ),
    'adminGetAllUsers' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Vec(UserPublic), 'err' : IDL.Text })],
        [],
      ),
    'adminGetAllWithdrawals' : IDL.Func(
        [IDL.Text, IDL.Text],
        [
          IDL.Variant({
            'ok' : IDL.Vec(WithdrawRequestPublic),
            'err' : IDL.Text,
          }),
        ],
        [],
      ),
    'adminGetAuditLog' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Vec(AuditLog), 'err' : IDL.Text })],
        [],
      ),
    'adminGetNotificationHistory' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Vec(NotificationPublic), 'err' : IDL.Text })],
        [],
      ),
    'adminGetPendingOrders' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Vec(OrderPublic), 'err' : IDL.Text })],
        [],
      ),
    'adminGetProducts' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Vec(ProductPublic), 'err' : IDL.Text })],
        [],
      ),
    'adminGetStats' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : AdminStats, 'err' : IDL.Text })],
        [],
      ),
    'adminLogin' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'adminRejectOrder' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'adminRejectWithdrawal' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'adminSendNotification' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(UserId), IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'adminUpdateProduct' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Nat, IDL.Opt(IDL.Text)],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'getDirectDownline' : IDL.Func([UserId], [IDL.Vec(UserPublic)], ['query']),
    'getDownlineTree' : IDL.Func(
        [UserId],
        [IDL.Variant({ 'ok' : TreeNode, 'err' : IDL.Text })],
        ['query'],
      ),
    'getMyNotifications' : IDL.Func(
        [UserId],
        [IDL.Vec(NotificationPublic)],
        ['query'],
      ),
    'getMyOrders' : IDL.Func([UserId], [IDL.Vec(OrderPublic)], ['query']),
    'getMyPaymentDetails' : IDL.Func(
        [UserId],
        [IDL.Variant({ 'ok' : PaymentDetails, 'err' : IDL.Text })],
        ['query'],
      ),
    'getMyProfile' : IDL.Func(
        [UserId],
        [IDL.Variant({ 'ok' : UserPublic, 'err' : IDL.Text })],
        ['query'],
      ),
    'getMyReferralCode' : IDL.Func([UserId], [IDL.Text], ['query']),
    'getMyWallet' : IDL.Func(
        [UserId],
        [IDL.Variant({ 'ok' : WalletInfo, 'err' : IDL.Text })],
        ['query'],
      ),
    'getMyWithdrawals' : IDL.Func(
        [UserId],
        [IDL.Vec(WithdrawRequestPublic)],
        ['query'],
      ),
    'getPlans' : IDL.Func([], [IDL.Vec(Plan)], ['query']),
    'getProducts' : IDL.Func([], [IDL.Vec(ProductPublic)], ['query']),
    'getUserByMobile' : IDL.Func([IDL.Text], [IDL.Opt(UserPublic)], ['query']),
    'loginUser' : IDL.Func(
        [IDL.Text, IDL.Text],
        [
          IDL.Variant({
            'ok' : IDL.Record({ 'userId' : UserId, 'profile' : UserPublic }),
            'err' : IDL.Text,
          }),
        ],
        [],
      ),
    'markNotificationRead' : IDL.Func(
        [UserId, IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'purchasePlan' : IDL.Func(
        [UserId, IDL.Nat, IDL.Text, IDL.Opt(IDL.Text)],
        [IDL.Variant({ 'ok' : OrderPublic, 'err' : IDL.Text })],
        [],
      ),
    'registerUser' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
        [IDL.Variant({ 'ok' : UserPublic, 'err' : IDL.Text })],
        [],
      ),
    'requestWithdrawal' : IDL.Func(
        [UserId, IDL.Nat],
        [IDL.Variant({ 'ok' : WithdrawRequestPublic, 'err' : IDL.Text })],
        [],
      ),
    'resetUserPassword' : IDL.Func(
        [IDL.Text, IDL.Text, UserId, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'savePaymentDetails' : IDL.Func(
        [UserId, IDL.Opt(BankDetails), IDL.Opt(IDL.Text)],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'setUserStatus' : IDL.Func(
        [IDL.Text, IDL.Text, UserId, UserStatus],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };