/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Plan {
    id: bigint;
    name: string;
    price: bigint;
}
export type Timestamp = bigint;
export interface AuditLog {
    id: bigint;
    action: string;
    timestamp: Timestamp;
    details: string;
    targetUserId?: UserId;
}
export interface UserPublic {
    id: UserId;
    status: UserStatus;
    referralCode: string;
    directIncome: bigint;
    hasBankDetails: boolean;
    hasUpiId: boolean;
    rightChild?: UserId;
    name: string;
    createdAt: Timestamp;
    sponsorId?: UserId;
    totalIncome: bigint;
    levelIncome: bigint;
    leftChild?: UserId;
    mobileNumber: string;
    isAdmin: boolean;
    pairIncome: bigint;
    walletBalance: bigint;
}
export interface ProductPublic {
    id: bigint;
    name: string;
    isActive: boolean;
    imageUrl?: string;
    price: bigint;
}
export interface TreeNode {
    name: string;
    user: UserId;
    children: Array<TreeNode>;
}
export interface OrderPublic {
    id: bigint;
    status: OrderStatus;
    deliveryAddress: string;
    planId: bigint;
    rejectionReason?: string;
    planPrice: bigint;
    timestamp: Timestamp;
    buyer: UserId;
    utrScreenshotUrl?: string;
}
export interface WithdrawRequestPublic {
    id: bigint;
    status: WithdrawStatus;
    user: UserId;
    processedAt?: Timestamp;
    amount: bigint;
    requestedAt: Timestamp;
}
export interface BankDetails {
    ifsc: string;
    accountHolderName: string;
    accountNumber: string;
}
export type UserId = Principal;
export interface AdminStats {
    totalOrders: bigint;
    pendingWithdrawals: bigint;
    pendingOrders: bigint;
    totalCommissionsPaid: bigint;
    totalUsers: bigint;
    totalRevenue: bigint;
    netProfit: bigint;
}
export interface WalletInfo {
    directIncome: bigint;
    balance: bigint;
    totalIncome: bigint;
    levelIncome: bigint;
    pairIncome: bigint;
}
export interface PaymentDetails {
    bankDetails?: BankDetails;
    upiId?: string;
}
export interface NotificationPublic {
    id: bigint;
    isRead: boolean;
    message: string;
    timestamp: Timestamp;
    recipientId?: UserId;
}
export enum OrderStatus {
    pendingApproval = "pendingApproval",
    approved = "approved",
    rejected = "rejected"
}
export enum UserStatus {
    active = "active",
    hold = "hold",
    inactive = "inactive"
}
export enum WithdrawStatus {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export interface backendInterface {
    adminAddProduct(name: string, price: bigint, imageUrl: string | null): Promise<{
        __kind__: "ok";
        ok: ProductPublic;
    } | {
        __kind__: "err";
        err: string;
    }>;
    adminApproveOrder(orderId: bigint): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    adminApproveWithdrawal(requestId: bigint): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    adminDeleteProduct(id: bigint): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    adminGetAllOrders(): Promise<{
        __kind__: "ok";
        ok: Array<OrderPublic>;
    } | {
        __kind__: "err";
        err: string;
    }>;
    adminGetAllUsers(): Promise<{
        __kind__: "ok";
        ok: Array<UserPublic>;
    } | {
        __kind__: "err";
        err: string;
    }>;
    adminGetAllWithdrawals(): Promise<{
        __kind__: "ok";
        ok: Array<WithdrawRequestPublic>;
    } | {
        __kind__: "err";
        err: string;
    }>;
    adminGetAuditLog(): Promise<{
        __kind__: "ok";
        ok: Array<AuditLog>;
    } | {
        __kind__: "err";
        err: string;
    }>;
    adminGetNotificationHistory(): Promise<{
        __kind__: "ok";
        ok: Array<NotificationPublic>;
    } | {
        __kind__: "err";
        err: string;
    }>;
    adminGetPendingOrders(): Promise<{
        __kind__: "ok";
        ok: Array<OrderPublic>;
    } | {
        __kind__: "err";
        err: string;
    }>;
    adminGetProducts(): Promise<{
        __kind__: "ok";
        ok: Array<ProductPublic>;
    } | {
        __kind__: "err";
        err: string;
    }>;
    adminGetStats(): Promise<{
        __kind__: "ok";
        ok: AdminStats;
    } | {
        __kind__: "err";
        err: string;
    }>;
    adminLogin(adminId: string, password: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    adminRejectOrder(orderId: bigint, reason: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    adminRejectWithdrawal(requestId: bigint): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    adminSendNotification(recipientId: UserId | null, message: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    adminUpdateProduct(id: bigint, name: string, price: bigint, imageUrl: string | null): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    getDirectDownline(): Promise<Array<UserPublic>>;
    getDownlineTree(): Promise<{
        __kind__: "ok";
        ok: TreeNode;
    } | {
        __kind__: "err";
        err: string;
    }>;
    getMyNotifications(): Promise<Array<NotificationPublic>>;
    getMyOrders(): Promise<Array<OrderPublic>>;
    getMyPaymentDetails(): Promise<{
        __kind__: "ok";
        ok: PaymentDetails;
    } | {
        __kind__: "err";
        err: string;
    }>;
    getMyProfile(): Promise<{
        __kind__: "ok";
        ok: UserPublic;
    } | {
        __kind__: "err";
        err: string;
    }>;
    getMyReferralCode(): Promise<string>;
    getMyWallet(): Promise<{
        __kind__: "ok";
        ok: WalletInfo;
    } | {
        __kind__: "err";
        err: string;
    }>;
    getMyWithdrawals(): Promise<Array<WithdrawRequestPublic>>;
    getPlans(): Promise<Array<Plan>>;
    getProducts(): Promise<Array<ProductPublic>>;
    getUserByMobile(mobileNumber: string): Promise<UserPublic | null>;
    /**
     * / Make the caller an admin if no admin exists yet.
     */
    initAdmin(): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    loginUser(mobileNumber: string, password: string): Promise<{
        __kind__: "ok";
        ok: {
            userId: UserId;
            profile: UserPublic;
        };
    } | {
        __kind__: "err";
        err: string;
    }>;
    markNotificationRead(notificationId: bigint): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    purchasePlan(productId: bigint, deliveryAddress: string, utrScreenshotUrl: string | null): Promise<{
        __kind__: "ok";
        ok: OrderPublic;
    } | {
        __kind__: "err";
        err: string;
    }>;
    registerUser(name: string, mobileNumber: string, password: string, sponsorCode: string | null): Promise<{
        __kind__: "ok";
        ok: UserPublic;
    } | {
        __kind__: "err";
        err: string;
    }>;
    requestWithdrawal(amount: bigint): Promise<{
        __kind__: "ok";
        ok: WithdrawRequestPublic;
    } | {
        __kind__: "err";
        err: string;
    }>;
    resetUserPassword(userId: UserId, newPassword: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    savePaymentDetails(bankDetails: BankDetails | null, upiId: string | null): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
    setUserStatus(userId: UserId, status: UserStatus): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
}
import type { AdminStats as _AdminStats, AuditLog as _AuditLog, BankDetails as _BankDetails, NotificationPublic as _NotificationPublic, OrderPublic as _OrderPublic, OrderStatus as _OrderStatus, PaymentDetails as _PaymentDetails, ProductPublic as _ProductPublic, Timestamp as _Timestamp, TreeNode as _TreeNode, UserId as _UserId, UserPublic as _UserPublic, UserStatus as _UserStatus, WalletInfo as _WalletInfo, WithdrawRequestPublic as _WithdrawRequestPublic, WithdrawStatus as _WithdrawStatus } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async adminAddProduct(arg0: string, arg1: bigint, arg2: string | null): Promise<{
        __kind__: "ok";
        ok: ProductPublic;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.adminAddProduct(arg0, arg1, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg2));
                return from_candid_variant_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminAddProduct(arg0, arg1, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg2));
            return from_candid_variant_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminApproveOrder(arg0: bigint): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.adminApproveOrder(arg0);
                return from_candid_variant_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminApproveOrder(arg0);
            return from_candid_variant_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminApproveWithdrawal(arg0: bigint): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.adminApproveWithdrawal(arg0);
                return from_candid_variant_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminApproveWithdrawal(arg0);
            return from_candid_variant_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminDeleteProduct(arg0: bigint): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.adminDeleteProduct(arg0);
                return from_candid_variant_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminDeleteProduct(arg0);
            return from_candid_variant_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminGetAllOrders(): Promise<{
        __kind__: "ok";
        ok: Array<OrderPublic>;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetAllOrders();
                return from_candid_variant_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetAllOrders();
            return from_candid_variant_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminGetAllUsers(): Promise<{
        __kind__: "ok";
        ok: Array<UserPublic>;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetAllUsers();
                return from_candid_variant_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetAllUsers();
            return from_candid_variant_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminGetAllWithdrawals(): Promise<{
        __kind__: "ok";
        ok: Array<WithdrawRequestPublic>;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetAllWithdrawals();
                return from_candid_variant_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetAllWithdrawals();
            return from_candid_variant_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminGetAuditLog(): Promise<{
        __kind__: "ok";
        ok: Array<AuditLog>;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetAuditLog();
                return from_candid_variant_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetAuditLog();
            return from_candid_variant_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminGetNotificationHistory(): Promise<{
        __kind__: "ok";
        ok: Array<NotificationPublic>;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetNotificationHistory();
                return from_candid_variant_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetNotificationHistory();
            return from_candid_variant_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminGetPendingOrders(): Promise<{
        __kind__: "ok";
        ok: Array<OrderPublic>;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetPendingOrders();
                return from_candid_variant_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetPendingOrders();
            return from_candid_variant_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminGetProducts(): Promise<{
        __kind__: "ok";
        ok: Array<ProductPublic>;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetProducts();
                return from_candid_variant_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetProducts();
            return from_candid_variant_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminGetStats(): Promise<{
        __kind__: "ok";
        ok: AdminStats;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetStats();
                return from_candid_variant_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetStats();
            return from_candid_variant_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminLogin(arg0: string, arg1: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.adminLogin(arg0, arg1);
                return from_candid_variant_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminLogin(arg0, arg1);
            return from_candid_variant_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminRejectOrder(arg0: bigint, arg1: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.adminRejectOrder(arg0, arg1);
                return from_candid_variant_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminRejectOrder(arg0, arg1);
            return from_candid_variant_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminRejectWithdrawal(arg0: bigint): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.adminRejectWithdrawal(arg0);
                return from_candid_variant_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminRejectWithdrawal(arg0);
            return from_candid_variant_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminSendNotification(arg0: UserId | null, arg1: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.adminSendNotification(to_candid_opt_n38(this._uploadFile, this._downloadFile, arg0), arg1);
                return from_candid_variant_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminSendNotification(to_candid_opt_n38(this._uploadFile, this._downloadFile, arg0), arg1);
            return from_candid_variant_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminUpdateProduct(arg0: bigint, arg1: string, arg2: bigint, arg3: string | null): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.adminUpdateProduct(arg0, arg1, arg2, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg3));
                return from_candid_variant_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminUpdateProduct(arg0, arg1, arg2, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg3));
            return from_candid_variant_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDirectDownline(): Promise<Array<UserPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDirectDownline();
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDirectDownline();
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDownlineTree(): Promise<{
        __kind__: "ok";
        ok: TreeNode;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getDownlineTree();
                return from_candid_variant_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDownlineTree();
            return from_candid_variant_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyNotifications(): Promise<Array<NotificationPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyNotifications();
                return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyNotifications();
            return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyOrders(): Promise<Array<OrderPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyOrders();
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyOrders();
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyPaymentDetails(): Promise<{
        __kind__: "ok";
        ok: PaymentDetails;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyPaymentDetails();
                return from_candid_variant_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyPaymentDetails();
            return from_candid_variant_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyProfile(): Promise<{
        __kind__: "ok";
        ok: UserPublic;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyProfile();
                return from_candid_variant_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyProfile();
            return from_candid_variant_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyReferralCode(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyReferralCode();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyReferralCode();
            return result;
        }
    }
    async getMyWallet(): Promise<{
        __kind__: "ok";
        ok: WalletInfo;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyWallet();
                return from_candid_variant_n48(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyWallet();
            return from_candid_variant_n48(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyWithdrawals(): Promise<Array<WithdrawRequestPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyWithdrawals();
                return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyWithdrawals();
            return from_candid_vec_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPlans(): Promise<Array<Plan>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlans();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlans();
            return result;
        }
    }
    async getProducts(): Promise<Array<ProductPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProducts();
                return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProducts();
            return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserByMobile(arg0: string): Promise<UserPublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserByMobile(arg0);
                return from_candid_opt_n49(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserByMobile(arg0);
            return from_candid_opt_n49(this._uploadFile, this._downloadFile, result);
        }
    }
    async initAdmin(): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.initAdmin();
                return from_candid_variant_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initAdmin();
            return from_candid_variant_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async loginUser(arg0: string, arg1: string): Promise<{
        __kind__: "ok";
        ok: {
            userId: UserId;
            profile: UserPublic;
        };
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.loginUser(arg0, arg1);
                return from_candid_variant_n50(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.loginUser(arg0, arg1);
            return from_candid_variant_n50(this._uploadFile, this._downloadFile, result);
        }
    }
    async markNotificationRead(arg0: bigint): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.markNotificationRead(arg0);
                return from_candid_variant_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markNotificationRead(arg0);
            return from_candid_variant_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async purchasePlan(arg0: bigint, arg1: string, arg2: string | null): Promise<{
        __kind__: "ok";
        ok: OrderPublic;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.purchasePlan(arg0, arg1, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg2));
                return from_candid_variant_n52(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.purchasePlan(arg0, arg1, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg2));
            return from_candid_variant_n52(this._uploadFile, this._downloadFile, result);
        }
    }
    async registerUser(arg0: string, arg1: string, arg2: string, arg3: string | null): Promise<{
        __kind__: "ok";
        ok: UserPublic;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.registerUser(arg0, arg1, arg2, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg3));
                return from_candid_variant_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerUser(arg0, arg1, arg2, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg3));
            return from_candid_variant_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async requestWithdrawal(arg0: bigint): Promise<{
        __kind__: "ok";
        ok: WithdrawRequestPublic;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.requestWithdrawal(arg0);
                return from_candid_variant_n53(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.requestWithdrawal(arg0);
            return from_candid_variant_n53(this._uploadFile, this._downloadFile, result);
        }
    }
    async resetUserPassword(arg0: UserId, arg1: string): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.resetUserPassword(arg0, arg1);
                return from_candid_variant_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resetUserPassword(arg0, arg1);
            return from_candid_variant_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async savePaymentDetails(arg0: BankDetails | null, arg1: string | null): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.savePaymentDetails(to_candid_opt_n54(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
                return from_candid_variant_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.savePaymentDetails(to_candid_opt_n54(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
            return from_candid_variant_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async setUserStatus(arg0: UserId, arg1: UserStatus): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.setUserStatus(arg0, to_candid_UserStatus_n55(this._uploadFile, this._downloadFile, arg1));
                return from_candid_variant_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setUserStatus(arg0, to_candid_UserStatus_n55(this._uploadFile, this._downloadFile, arg1));
            return from_candid_variant_n6(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_AuditLog_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AuditLog): AuditLog {
    return from_candid_record_n30(_uploadFile, _downloadFile, value);
}
function from_candid_NotificationPublic_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NotificationPublic): NotificationPublic {
    return from_candid_record_n34(_uploadFile, _downloadFile, value);
}
function from_candid_OrderPublic_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderPublic): OrderPublic {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_OrderStatus_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderStatus): OrderStatus {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentDetails_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentDetails): PaymentDetails {
    return from_candid_record_n45(_uploadFile, _downloadFile, value);
}
function from_candid_ProductPublic_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProductPublic): ProductPublic {
    return from_candid_record_n4(_uploadFile, _downloadFile, value);
}
function from_candid_TreeNode_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TreeNode): TreeNode {
    return from_candid_record_n41(_uploadFile, _downloadFile, value);
}
function from_candid_UserPublic_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserPublic): UserPublic {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_UserStatus_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserStatus): UserStatus {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_WithdrawRequestPublic_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WithdrawRequestPublic): WithdrawRequestPublic {
    return from_candid_record_n23(_uploadFile, _downloadFile, value);
}
function from_candid_WithdrawStatus_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WithdrawStatus): WithdrawStatus {
    return from_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserId]): UserId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Timestamp]): Timestamp | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_BankDetails]): BankDetails | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserPublic]): UserPublic | null {
    return value.length === 0 ? null : from_candid_UserPublic_n15(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _OrderStatus;
    deliveryAddress: string;
    planId: bigint;
    rejectionReason: [] | [string];
    planPrice: bigint;
    timestamp: _Timestamp;
    buyer: _UserId;
    utrScreenshotUrl: [] | [string];
}): {
    id: bigint;
    status: OrderStatus;
    deliveryAddress: string;
    planId: bigint;
    rejectionReason?: string;
    planPrice: bigint;
    timestamp: Timestamp;
    buyer: UserId;
    utrScreenshotUrl?: string;
} {
    return {
        id: value.id,
        status: from_candid_OrderStatus_n11(_uploadFile, _downloadFile, value.status),
        deliveryAddress: value.deliveryAddress,
        planId: value.planId,
        rejectionReason: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.rejectionReason)),
        planPrice: value.planPrice,
        timestamp: value.timestamp,
        buyer: value.buyer,
        utrScreenshotUrl: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.utrScreenshotUrl))
    };
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _UserId;
    status: _UserStatus;
    referralCode: string;
    directIncome: bigint;
    hasBankDetails: boolean;
    hasUpiId: boolean;
    rightChild: [] | [_UserId];
    name: string;
    createdAt: _Timestamp;
    sponsorId: [] | [_UserId];
    totalIncome: bigint;
    levelIncome: bigint;
    leftChild: [] | [_UserId];
    mobileNumber: string;
    isAdmin: boolean;
    pairIncome: bigint;
    walletBalance: bigint;
}): {
    id: UserId;
    status: UserStatus;
    referralCode: string;
    directIncome: bigint;
    hasBankDetails: boolean;
    hasUpiId: boolean;
    rightChild?: UserId;
    name: string;
    createdAt: Timestamp;
    sponsorId?: UserId;
    totalIncome: bigint;
    levelIncome: bigint;
    leftChild?: UserId;
    mobileNumber: string;
    isAdmin: boolean;
    pairIncome: bigint;
    walletBalance: bigint;
} {
    return {
        id: value.id,
        status: from_candid_UserStatus_n17(_uploadFile, _downloadFile, value.status),
        referralCode: value.referralCode,
        directIncome: value.directIncome,
        hasBankDetails: value.hasBankDetails,
        hasUpiId: value.hasUpiId,
        rightChild: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.rightChild)),
        name: value.name,
        createdAt: value.createdAt,
        sponsorId: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.sponsorId)),
        totalIncome: value.totalIncome,
        levelIncome: value.levelIncome,
        leftChild: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.leftChild)),
        mobileNumber: value.mobileNumber,
        isAdmin: value.isAdmin,
        pairIncome: value.pairIncome,
        walletBalance: value.walletBalance
    };
}
function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _WithdrawStatus;
    user: _UserId;
    processedAt: [] | [_Timestamp];
    amount: bigint;
    requestedAt: _Timestamp;
}): {
    id: bigint;
    status: WithdrawStatus;
    user: UserId;
    processedAt?: Timestamp;
    amount: bigint;
    requestedAt: Timestamp;
} {
    return {
        id: value.id,
        status: from_candid_WithdrawStatus_n24(_uploadFile, _downloadFile, value.status),
        user: value.user,
        processedAt: record_opt_to_undefined(from_candid_opt_n26(_uploadFile, _downloadFile, value.processedAt)),
        amount: value.amount,
        requestedAt: value.requestedAt
    };
}
function from_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    action: string;
    timestamp: _Timestamp;
    details: string;
    targetUserId: [] | [_UserId];
}): {
    id: bigint;
    action: string;
    timestamp: Timestamp;
    details: string;
    targetUserId?: UserId;
} {
    return {
        id: value.id,
        action: value.action,
        timestamp: value.timestamp,
        details: value.details,
        targetUserId: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.targetUserId))
    };
}
function from_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    isRead: boolean;
    message: string;
    timestamp: _Timestamp;
    recipientId: [] | [_UserId];
}): {
    id: bigint;
    isRead: boolean;
    message: string;
    timestamp: Timestamp;
    recipientId?: UserId;
} {
    return {
        id: value.id,
        isRead: value.isRead,
        message: value.message,
        timestamp: value.timestamp,
        recipientId: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.recipientId))
    };
}
function from_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    name: string;
    isActive: boolean;
    imageUrl: [] | [string];
    price: bigint;
}): {
    id: bigint;
    name: string;
    isActive: boolean;
    imageUrl?: string;
    price: bigint;
} {
    return {
        id: value.id,
        name: value.name,
        isActive: value.isActive,
        imageUrl: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.imageUrl)),
        price: value.price
    };
}
function from_candid_record_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    user: _UserId;
    children: Array<_TreeNode>;
}): {
    name: string;
    user: UserId;
    children: Array<TreeNode>;
} {
    return {
        name: value.name,
        user: value.user,
        children: from_candid_vec_n42(_uploadFile, _downloadFile, value.children)
    };
}
function from_candid_record_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bankDetails: [] | [_BankDetails];
    upiId: [] | [string];
}): {
    bankDetails?: BankDetails;
    upiId?: string;
} {
    return {
        bankDetails: record_opt_to_undefined(from_candid_opt_n46(_uploadFile, _downloadFile, value.bankDetails)),
        upiId: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.upiId))
    };
}
function from_candid_record_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userId: _UserId;
    profile: _UserPublic;
}): {
    userId: UserId;
    profile: UserPublic;
} {
    return {
        userId: value.userId,
        profile: from_candid_UserPublic_n15(_uploadFile, _downloadFile, value.profile)
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pendingApproval: null;
} | {
    approved: null;
} | {
    rejected: null;
}): OrderStatus {
    return "pendingApproval" in value ? OrderStatus.pendingApproval : "approved" in value ? OrderStatus.approved : "rejected" in value ? OrderStatus.rejected : value;
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: Array<_UserPublic>;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Array<UserPublic>;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_vec_n14(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    hold: null;
} | {
    inactive: null;
}): UserStatus {
    return "active" in value ? UserStatus.active : "hold" in value ? UserStatus.hold : "inactive" in value ? UserStatus.inactive : value;
}
function from_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _ProductPublic;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: ProductPublic;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_ProductPublic_n3(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: Array<_WithdrawRequestPublic>;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Array<WithdrawRequestPublic>;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_vec_n21(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): WithdrawStatus {
    return "pending" in value ? WithdrawStatus.pending : "approved" in value ? WithdrawStatus.approved : "rejected" in value ? WithdrawStatus.rejected : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: Array<_AuditLog>;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Array<AuditLog>;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_vec_n28(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: Array<_NotificationPublic>;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Array<NotificationPublic>;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_vec_n32(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: Array<_ProductPublic>;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Array<ProductPublic>;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_vec_n36(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _AdminStats;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: AdminStats;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _TreeNode;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: TreeNode;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_TreeNode_n40(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _PaymentDetails;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: PaymentDetails;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_PaymentDetails_n44(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _UserPublic;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: UserPublic;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_UserPublic_n15(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _WalletInfo;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: WalletInfo;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: {
        userId: _UserId;
        profile: _UserPublic;
    };
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: {
        userId: UserId;
        profile: UserPublic;
    };
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_record_n51(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _OrderPublic;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: OrderPublic;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_OrderPublic_n9(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _WithdrawRequestPublic;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: WithdrawRequestPublic;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_WithdrawRequestPublic_n22(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: Array<_OrderPublic>;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Array<OrderPublic>;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_vec_n8(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserPublic>): Array<UserPublic> {
    return value.map((x)=>from_candid_UserPublic_n15(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_WithdrawRequestPublic>): Array<WithdrawRequestPublic> {
    return value.map((x)=>from_candid_WithdrawRequestPublic_n22(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AuditLog>): Array<AuditLog> {
    return value.map((x)=>from_candid_AuditLog_n29(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_NotificationPublic>): Array<NotificationPublic> {
    return value.map((x)=>from_candid_NotificationPublic_n33(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ProductPublic>): Array<ProductPublic> {
    return value.map((x)=>from_candid_ProductPublic_n3(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TreeNode>): Array<TreeNode> {
    return value.map((x)=>from_candid_TreeNode_n40(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_OrderPublic>): Array<OrderPublic> {
    return value.map((x)=>from_candid_OrderPublic_n9(_uploadFile, _downloadFile, x));
}
function to_candid_UserStatus_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserStatus): _UserStatus {
    return to_candid_variant_n56(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserId | null): [] | [_UserId] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BankDetails | null): [] | [_BankDetails] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_variant_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserStatus): {
    active: null;
} | {
    hold: null;
} | {
    inactive: null;
} {
    return value == UserStatus.active ? {
        active: null
    } : value == UserStatus.hold ? {
        hold: null
    } : value == UserStatus.inactive ? {
        inactive: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
